'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { FiEdit2, FiFileText, FiPlus, FiSearch, FiTrash2, FiEye, FiClock } from 'react-icons/fi';
import { getAuthHeader } from '@/lib/clientAuth';
import { AdminNotice, ConfirmDialog } from '@/components/admin/AdminDialog';

export default function ArticlesPage() {
  const [posts, setPosts] = useState([]); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [pendingDelete, setPendingDelete] = useState(null); const [notice, setNotice] = useState(() => { if (typeof window === 'undefined') return ''; const message = sessionStorage.getItem('adminArticlesNotice') || ''; sessionStorage.removeItem('adminArticlesNotice'); return message; });
  const load = () => fetch('/api/blog/posts?admin=true', { headers: getAuthHeader() }).then((r) => r.json()).then((data) => setPosts(data.posts || []));
  useEffect(() => { load(); }, []);
  const visiblePosts = useMemo(() => posts.filter((post) => (filter === 'all' || post.status === filter) && post.titleFr.toLowerCase().includes(query.toLowerCase())), [posts, query, filter]);
  const remove = async () => { if (!pendingDelete) return; const response = await fetch(`/api/blog/posts/${pendingDelete}`, { method: 'DELETE', headers: getAuthHeader() }); setPendingDelete(null); if (!response.ok) return setNotice('La suppression de l’article a échoué.'); load(); setNotice('Article supprimé avec succès.'); };
  const published = posts.filter((post) => post.status === 'published').length;
  return <><div className="admin-page max-w-6xl mx-auto"><div className="admin-articles-hero"><div><p className="admin-kicker">CONTENU ÉDITORIAL</p><h1>Gestionnaire d’articles</h1><p>Créez, organisez et publiez les contenus du blog KK SMART COM.</p></div><Link href="/admin/articles/nouveau" className="admin-primary-action"><FiPlus /> Nouvel article</Link></div><section className="admin-article-metrics"><div><FiFileText /><span><b>{posts.length}</b> articles</span></div><div><FiEye /><span><b>{published}</b> publiés</span></div><div><FiClock /><span><b>{posts.length - published}</b> brouillons</span></div></section><section className="admin-table-panel"><div className="admin-table-toolbar"><div className="admin-search"><FiSearch /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un article…" /></div><div className="admin-segmented"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>Tous</button><button className={filter === 'published' ? 'active' : ''} onClick={() => setFilter('published')}>Publiés</button><button className={filter === 'draft' ? 'active' : ''} onClick={() => setFilter('draft')}>Brouillons</button></div></div><div className="overflow-x-auto"><table className="admin-articles-table"><thead><tr><th>Article</th><th>Taxonomie</th><th>Statut</th><th>Dernière mise à jour</th><th aria-label="Actions" /></tr></thead><tbody>{visiblePosts.map((post) => <tr key={post.id}><td><div className="article-cell"><div className="article-mark"><FiFileText /></div><div><Link href={`/admin/articles/${post.id}`}>{post.titleFr}</Link><small>{post.titleEn || 'Traduction EN non renseignée'}</small></div></div></td><td><span className="taxonomy-pill">{post.department?.nameFr || 'Sans département'}</span></td><td><span className={`status-pill ${post.status}`}>{post.status === 'published' ? 'Publié' : 'Brouillon'}</span></td><td><span className="date-cell">{post.updatedAt ? new Date(post.updatedAt).toLocaleDateString('fr-FR', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'}</span></td><td><div className="table-actions"><Link title="Modifier" href={`/admin/articles/${post.id}`}><FiEdit2 /></Link><button title="Supprimer" onClick={() => setPendingDelete(post.id)}><FiTrash2 /></button></div></td></tr>)}</tbody></table></div>{!visiblePosts.length && <div className="admin-empty-state"><FiFileText /><h2>Aucun article trouvé</h2><p>{query ? 'Essayez une autre recherche.' : 'Commencez par créer votre premier article éditorial.'}</p>{!query && <Link href="/admin/articles/nouveau">Créer un article</Link>}</div>}</section></div><ConfirmDialog open={Boolean(pendingDelete)} danger title="Supprimer cet article ?" description="Cette action est définitive. Le contenu ne pourra pas être récupéré." confirmLabel="Supprimer l’article" onClose={() => setPendingDelete(null)} onConfirm={remove}/><AdminNotice message={notice} onClose={() => setNotice('')}/></>;
}
