'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import ImageUploader from '@/components/ui/ImageUploader';
import RichTextEditor from '@/components/ui/RichTextEditor';
import { getAuthHeader } from '@/lib/clientAuth';

const initial = { titleFr:'', titleEn:'', summaryFr:'', summaryEn:'', introductionFr:'', introductionEn:'', bodyFr:'', bodyEn:'', conclusionFr:'', conclusionEn:'', coverImage:'', departmentId:'', subcategoryId:'', status:'draft', sectionsFr:[], sectionsEn:[] };

export default function ArticleEditor() {
  const { id } = useParams(); const router = useRouter(); const isNew = id === 'nouveau';
  const [form, setForm] = useState(initial); const [categories, setCategories] = useState([]); const [loading, setLoading] = useState(!isNew);
  useEffect(() => { fetch('/api/blog/departments', { headers: getAuthHeader() }).then(r=>r.json()).then(d=>setCategories(d.departments || [])); if (!isNew) fetch(`/api/blog/posts/${id}?admin=true`, { headers:getAuthHeader() }).then(r=>r.json()).then(d=>d.post && setForm({...initial,...d.post,departmentId:d.post.departmentId||'',subcategoryId:d.post.subcategoryId||'',sectionsFr:d.post.sectionsFr||[],sectionsEn:d.post.sectionsEn||[]})).finally(()=>setLoading(false)); }, [id,isNew]);
  const update = (key, value) => setForm(current => ({...current,[key]:value}));
  const category = categories.find(item => item.id === Number(form.departmentId));
  const save = async (event) => { event.preventDefault(); const response = await fetch(isNew ? '/api/blog/posts' : `/api/blog/posts/${id}`, { method:isNew?'POST':'PUT', headers:{'Content-Type':'application/json',...getAuthHeader()}, body:JSON.stringify(form) }); const data=await response.json(); if(!response.ok) { console.error(data.message || 'Erreur'); return; } sessionStorage.setItem('adminArticlesNotice', isNew ? 'Article ajouté avec succès.' : 'Article modifié avec succès.'); router.push('/admin/articles'); };
  const section = (locale, index, key, value) => update(locale, form[locale].map((item,n)=>n===index?{...item,[key]:value}:item));
  const addSection = (locale) => update(locale, [...form[locale], {id:crypto.randomUUID(),title:'',content:''}]);
  const editor = (locale, label) => <div className="space-y-2"><h2 className="font-semibold">{label}</h2><RichTextEditor value={form[locale]||''} onChange={value=>update(locale,value)} /></div>;
  const sectionEditor = (locale, label) => <div className="space-y-3"><div className="flex justify-between"><h2 className="font-semibold">{label}</h2><button type="button" onClick={()=>addSection(locale)}>+ Ajouter</button></div>{form[locale].map((item,index)=><div key={item.id} className="border p-3 rounded space-y-2"><input className="border p-2 rounded w-full" placeholder="Titre" value={item.title} onChange={e=>section(locale,index,'title',e.target.value)} /><RichTextEditor value={item.content} onChange={value=>section(locale,index,'content',value)} /><button type="button" className="text-red-600" onClick={()=>update(locale,form[locale].filter((_,n)=>n!==index))}>Supprimer</button></div>)}</div>;
  if (loading) return <p className="p-6">Chargement…</p>;
  return <form onSubmit={save} className="p-6 max-w-5xl mx-auto space-y-6"><div className="flex justify-between"><h1 className="text-3xl font-bold">{isNew?'Nouvel article':'Modifier l’article'}</h1><div><Link href="/admin/articles" className="mr-3">Annuler</Link><button className="px-4 py-2 bg-blue-600 text-white rounded">Enregistrer</button></div></div><div className="grid md:grid-cols-2 gap-4"><input required className="border p-2 rounded" placeholder="Titre FR *" value={form.titleFr} onChange={e=>update('titleFr',e.target.value)} /><input className="border p-2 rounded" placeholder="Titre EN" value={form.titleEn||''} onChange={e=>update('titleEn',e.target.value)} /><textarea className="border p-2 rounded" placeholder="Résumé FR" value={form.summaryFr||''} onChange={e=>update('summaryFr',e.target.value)} /><textarea className="border p-2 rounded" placeholder="Résumé EN" value={form.summaryEn||''} onChange={e=>update('summaryEn',e.target.value)} /><select className="border p-2 rounded" value={form.departmentId} onChange={e=>{update('departmentId',e.target.value);update('subcategoryId','')}}><option value="">Département</option>{categories.map(item=><option value={item.id} key={item.id}>{item.nameFr}</option>)}</select><select className="border p-2 rounded" value={form.subcategoryId} onChange={e=>update('subcategoryId',e.target.value)}><option value="">Sous-catégorie</option>{(category?.subcategories||[]).map(item=><option value={item.id} key={item.id}>{item.nameFr}</option>)}</select><select className="border p-2 rounded" value={form.status} onChange={e=>update('status',e.target.value)}><option value="draft">Brouillon</option><option value="published">Publié</option></select></div><ImageUploader labelCover="Image de couverture" value={form.coverImage||''} onChange={value=>update('coverImage',value)} />{editor('introductionFr','Introduction FR')}{editor('introductionEn','Introduction EN')}{editor('bodyFr','Corps FR')}{editor('bodyEn','Corps EN')}{sectionEditor('sectionsFr','Sections dynamiques FR')}{sectionEditor('sectionsEn','Sections dynamiques EN')}{editor('conclusionFr','Conclusion FR')}{editor('conclusionEn','Conclusion EN')}</form>;
}
